workflows:
  ios-testflight:
    name: iOS TestFlight (Flutter)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: de.driveassistant.ar
        APPLE_TEAM_ID: QLQ959FUNR
      ios_signing:
        distribution_type: app_store
        bundle_identifier: de.driveassistant.ar

    integrations:
      app_store_connect: DriveBot

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Toolchain diagnostics
        script: |
          set -e
          flutter --version
          dart --version
          xcodebuild -version

      - name: Flutter clean
        script: flutter clean

      - name: Resolve Flutter dependencies
        script: flutter pub get

     # - name: Verify formatting
     #   script: dart format --output=none --set-exit-if-changed .

      - name: Static analysis
        script: flutter analyze

      - name: Unit and widget tests
        script: flutter test


      - name: Clean and install CocoaPods
        script: |
          rm -rf ios/Pods
          rm -f ios/Pods/Manifest.lock
          cd ios
          pod install --repo-update
          cd ..

      - name: Prepare iOS project without code signing
        script: |
          flutter build ios \
            --release \
            --no-codesign

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.0.$PROJECT_BUILD_NUMBER \
            --build-number=$PROJECT_BUILD_NUMBER \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
